name: ci

on:
  schedule:
    - cron: '36 20 * * *'  # 每天定时构建
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]  # 版本标签触发
  pull_request:
    branches: [ "main" ]

env:
  # 支持 Docker Hub 和 GitHub Container Registry
  DOCKER_HUB_REGISTRY: docker.io
  GHCR_REGISTRY: ghcr.io
  IMAGE_NAME: yyc3-gpu-builder
  DOCKER_HUB_IMAGE: ${{ vars.DOCKER_USER }}/${{ env.IMAGE_NAME }}
  GHCR_IMAGE: ${{ env.GHCR_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write  # 用于 cosign 签名
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 cosign 工具（非 PR 时）
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
        with:
          cosign-release: 'v2.2.4'

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
        with:
          driver: cloud
          endpoint: "yanyuit/yyc3-gpu-builder"
          install: true

      # 登录 Docker Hub（非 PR 时）
      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.DOCKER_HUB_REGISTRY }}
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      # 登录 GitHub Container Registry（非 PR 时）
      - name: Log into GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 提取 Docker 元数据
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: |
            ${{ env.DOCKER_HUB_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch
            type=ref,event=tag
            type=sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "yanyuit/yyc3-gpu-builder"
          install: true
      # 构建和推送 Docker 镜像
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}

      # 签名已发布的 Docker 镜像（非 PR 时）
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}